# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 033534752e9117be2f642bb9880e188ce0eaeb9b79ee29139d918b388825cd66e322fa2d2c858252ad2ace6a03d353c0a3af3b2425bae4f39f945afe7917a0c3

test:
  secret_key_base: 28626898475801afd815e12b20487a65c565ea28c0265bf27c026c73ea8fb2e7ef695a2cc28fd53cffdcb6a66b4ecfd815d2a1667b2c27fb6a67c1510443d3e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
